### PR TITLE
minor bugfix on help menu

### PR DESCRIPTION
**Pull request by at669**
forgot to restart help menu pagination after leaving the menu

### CODE REVIEW

**Comment by at669** [comment]
wait never mind, the buttons are temp broken, one minute

**Comment by at669** [comment]
nope, found another issue with the buttons, sorry! one more minute

**Comment by at669** [comment]
okay. okay. i fixed it for real this time i think. the buttons were disappearing periodically due to the inconsistent indexing.

**Comment by at669** [comment]
@XalkXolc oh no, this is weird because it looks fine on devices. let me check what my mac build does

**Comment by at669** [comment]
> @XalkXolc Upon reentering the help menu, buttons are not visible. Upon clicking one, only the back button becomes visible.

actually, this looks fine on mac too. are you getting any messages about things being out of bounds or something?

**Comment by XalkXolc** [comment]
WAIT NOT IT'S NOT
It happens if you exit on the last help screen

**Comment by XalkXolc** [comment]
Ok I fixed it

**Pull request merged**
