### PR TITLE
disables buttons, anims during pause, win, loss screens

### PR DESCRIPTION
**Pull request by XalkXolc**

### CODE REVIEW

**Comment by David-Arcia** [comment]
I approve.  You might want to check with Emma/Jon about game logic and animations.

**Comment by XalkXolc** [comment]
On top of disabling menu buttons when outside of Menu Scene, also fixes some bugs:
InitStacks not properly initializing stackSize on reloading a level
Staying in win/loss state when loading new level

**Comment by at669** [comment]
not sure if this was already like this before, but credits back button breaks (credits is not a new scene, just drawn within menuscene) so it seems to be disabling with the credits button press? if you're not already doing this, i can fix the pause screen deactivation 

also, what is LISTENER_ID 100 in menuscene? if these listeners overlap with the button listeners, 100 is already reserved for the menu play button

**Comment by XalkXolc** [comment]
I'll take a look at the back button, see what's going on there.
As for LISTENER_ID, it's a constant used in setActive() used to reference the relevant buttons. I set it to 100 because that's where it starts when activating/deactivating the buttons in the _buttons map.

**Comment by XalkXolc** [comment]
Okay, I realized I shouldn't have been deactivating the back button because it already has its own deactivation going on. Also yes if you could do the pause screen deactivation @at669 , it would be appreciated.

**Pull request merged**
